### ISSUE TITLE
Uncaught Error: Cannot find module "react-undraw"

### ISSUE THREAD

**Issue by masudhossain** [justinlettau/react-undraw#47]
## Type
What kind of issue is this?

```
[x] Bug report.
[ ] Feature request.
```

## Current Behavior

Added `import Undraw from 'react-undraw'` to a page and i get the error. 

## Expected behavior

Module error should not occur given that react-undraw is on package.json. 

## Steps to Reproduce

`npm install react-undraw`

**Comment by marklawlor** [comment]
@masudhossain I just did a clean install on a few different machines with the latest version of this library didn't run into any issues, and our CI is passing which always does a clean install.

Possibly this is an issue with your local setup. Maybe run `npm ci` to get a clean install of your `node_modules`

**Comment by msiric** [comment]
@marklawlor I'm running into the same issue using Yarn. I tried `yarn cache clean` and reinstalling node_modules but that didn't help either.

**Comment by marklawlor** [comment]
> @marklawlor I'm running into the same issue using Yarn. I tried `yarn cache clean` and reinstalling node_modules but that didn't help either.

@msiric Currently npm is showing 555 successful downloads this week https://www.npmjs.com/package/react-undraw

If the error message you are receiving is `Cannot find module "react-undraw"` you should isolate that issue more within your environment. Some simple steps

1. Can you install it on a different computer. If you don't have a second computer, every Github Repo comes with Github Actions which provides you with a environment to test to install.
1. Check for a spelling / user error
1. Are you using the default registry?
1. Are you trying to install a version that is not on npm?
1. Can you install it with `npm` and not `yarn`?

If your not getting that exact error message, you should create a new issue with the new error message.

**Comment by msiric** [comment]
1. I tried installing on three different machines running Windows 10/Fedora/macOS and got an error on all of them
2. I checked for spelling errors and found none. After all, I'm just importing the package `import Undraw from "react-undraw";`
3. Yes
4. I assume I'm using the latest version by running `yarn add react-undraw`
5. I just tried installing with npm and the same error is being thrown

I've never had such an issue with any other package. Not sure what's causing this.

**Comment by marklawlor** [comment]
Can you attach your yarn or npm error log?

**Comment by msiric** [comment]
No error log, just "Module not found: Can't resolve 'react-undraw' in 'react_app/src/pages/Home'"
I found the package in my node_modules folder so my guess is that there is an issue linking the import statement to the actual path of the module.

**Comment by marklawlor** [comment]
> No error log, just "Module not found: Can't resolve 'react-undraw' in 'react_app/src/pages/Home'"
> I found the package in my node_modules folder so my guess is that there is an issue linking the import statement to the actual path of the module.

Correct, so that suggests an issue with your local environment. I would read the troubleshooting docs on the yarn website (I'm guessing your having a problem with yarn `Plug and Play` not linking the module), otherwise ask on stackoverflow. Another step would be to create a new hello-world project and see if you can get it working there, might just be a problem with that 1 projects config (your maybe your `yarnrc` or `pnp.js` file)

I don't use yarn myself so I don't think I can be any further help apart from general troubleshooting advise.

**Comment by msiric** [comment]
Just tried creating a new project from scratch using `npx create-react-app` with Node v14 and still getting the same error.
This suggests that it's not an issue with the local env.
Please note that the error doesn't appear until you import the module inside the app (`import Undraw from "react-undraw";`).

**Comment by marklawlor** [comment]
@msiric  Are you 100% sure that there are no other error messages? I think I can replicate your issue, but I'm also getting the error message. You will get this error when ever you try and install the package or build new images.

```
Generating unDraw components ...
Component built: "UndrawCoding"
(node:18080) UnhandledPromiseRejectionWarning: Error: Command failed: tsc -p ./tsconfig.json
/bin/sh: 1: tsc: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12)
```

Because `react-undraw` doesn;t built properly it is also not available at runtime.

This is a bit more obvious to fix, this library requires Typescript as a install time dependency, but I don't think that is properly documented anywhere.

**Comment by ronaldlangeveld** [comment]
Had the same issue.

Ran `npm install -g typescript` and then installed React-Undraw again and it built fine. 

So yea, maybe add the typescript dependency somewhere in the docs.
